name: Run News Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_urls.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python src/fetch_urls.py
  
      - name: Run scrape_full_articles.py
        run: python src/scrape_full_articles.py
  
      - name: Run embed_articles.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python src/embed_articles.py

      - name: Commit and push generated data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/articles/* data/full_text/* data/vector_store/*
          git commit -m "Add new articles and full text fo